function setFigureProperties(plot_arr, legend_names, title_str, xlabel_str, ylabel_str, varargin)
	% Using this function we will
	% achieve consistent figure style everywhere.
	% You can specify legend location in optional 'legend_location' parameter
	% 

	[legend_location] = process_options(varargin, 'legend_location', []);
	if (isempty(legend_location))
		hLegend = legend(plot_arr, legend_names);
	else
		hLegend = legend(plot_arr, legend_names, 'location', legend_location);
	end
	hTitle = title(title_str);
	hXLabel = xlabel(xlabel_str);
	hYLabel = ylabel(ylabel_str);
	set( gca                       , ...
	    'FontName'   , 'Helvetica' );
	set([hTitle, hXLabel, hYLabel], ...
	    'FontName'   , 'AvantGarde');
	set([hLegend]                 , ...
	    'FontSize'   , 11          );
	set([hXLabel, hYLabel]  , ...
	    'FontSize'   , 10          );
	set( hTitle                    , ...
	    'FontSize'   , 12          , ...
	    'FontWeight' , 'bold'      );
	set(gca, ...
		'Box'         , 'off'     , ...
		'TickDir'     , 'out'     , ...
		'TickLength'  , [.02 .02] , ...
		'XMinorTick'  , 'on'      , ...
		'YMinorTick'  , 'on'      , ...
		'YGrid'       , 'on'      , ...
		'XColor'      , [.3 .3 .3], ...
		'YColor'      , [.3 .3 .3], ...
		'LineWidth'   , 1         );
end
